name: Build README

on:
  schedule:
    - cron: "0/5 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.3

      - name: Update README
        run: |-
          node updateReadme.mjs
          cat README.md
      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "rightonhana@gmail.com"
          git config --global user.name "Florencia Gonzalez"
          git add -A
          git commit -m ":bento: update avatar" || exit 0
          git push
